# Generated by Django 5.2.8 on 2025-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
