# Generated by Django 5.2.8 on 2025-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
