# Generated by Django 5.2.8 on 2025-11-19 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: Evim, İş Yerim', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('address_text', models.TextField()),
                ('billing_type', models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal')], default='individual', max_length=10)),
                ('tc_id', models.CharField(blank=True, help_text='Bireysel fatura için TC Kimlik No', max_length=11, null=True)),
                ('corporate_name', models.CharField(blank=True, help_text='Kurumsal fatura için Şirket Adı', max_length=100, null=True)),
                ('tax_office', models.CharField(blank=True, help_text='Kurumsal fatura için Vergi Dairesi', max_length=50, null=True)),
                ('tax_number', models.CharField(blank=True, help_text='Kurumsal fatura için Vergi Numarası', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
