# Generated by Django 5.2.8 on 2025-11-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productcolor_productimage_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Koleksiyon adı (örn: Bahar 2024, Modern Ofis)', max_length=100)),
                ('slug', models.SlugField(help_text='URL için benzersiz kısa isim', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Koleksiyon açıklaması', null=True)),
                ('image', models.ImageField(blank=True, help_text='Koleksiyon kapak görseli', null=True, upload_to='collections/')),
                ('is_active', models.BooleanField(default=True, help_text='Koleksiyon aktif mi?')),
                ('order', models.IntegerField(default=0, help_text='Sıralama (küçükten büyüğe)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Collections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Bu ürünün ait olduğu koleksiyonlar', related_name='products', to='api.collection'),
        ),
    ]
