# Generated by Django 5.2.8 on 2025-11-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_collection_product_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collections',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Bu ürünün ait olduğu koleksiyon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.collection'),
        ),
    ]
