# Generated by Django 5.2.8 on 2025-11-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_product_collections_product_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kupon kodu (örn: YAZ2024)', max_length=50, unique=True)),
                ('discount_percent', models.IntegerField(help_text='İndirim yüzdesi (örn: 10 için %10)')),
                ('is_active', models.BooleanField(default=True, help_text='Kupon aktif mi?')),
                ('valid_from', models.DateTimeField(help_text='Geçerlilik başlangıç tarihi')),
                ('valid_to', models.DateTimeField(help_text='Geçerlilik bitiş tarihi')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Toplam kullanım limiti (Boş bırakılırsa limitsiz)', null=True)),
                ('used_count', models.IntegerField(default=0, help_text='Kullanılma sayısı')),
            ],
        ),
    ]
