# Generated by Django 5.2.8 on 2025-12-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Ödeme Bekleniyor'), ('order_confirmed', 'Sipariş Onaylandı'), ('preparing', 'Üretime Hazırlanıyor'), ('metalworks', 'Metal İşçiliği'), ('woodworks', 'Ahşap İşçiliği'), ('finishing', 'Boya & Vernik'), ('quality_control', 'Kalite Kontrol'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal/İade')], default='pending_payment', max_length=20),
        ),
    ]
